name: delniit_utils
description: My Delniit utility functions ported to dart
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.0
  import_sorter: any

import_sorter:
  comments: false

